### ISSUE TITLE
Omitting Optional params in request causes error

### ISSUE THREAD

**Issue by amricko0b** [input-output-hk/armadillo#39]
Greetings! I'm very happy to find such an awesome JSON-RPC tool for Scala. My thanks and respect to all creators and contributors.

**Describe the bug**
When optional param omitted in request, server fails to handle it. 
It responds with:
```
{
	"jsonrpc": "2.0",
	"error": {
		"code": -32602,
		"message": "Invalid params"
	},
	"id": "..."
}
```

Adding Logging interceptor showed that there is a decoding exception: `Error(Too many inputs provided,java.lang.RuntimeException: Too many inputs provided)`.

I suppose, this happens because of actual params check here (ServerInterpreter.scala):

```
  private def combineDecodeAsObject(in: Vector[JsonRpcIO.Single[_]]): Json.JsonObject[Raw] => DecodeResult[Vector[_]] = { json =>
    val jsonAsMap = json.fields.toMap
    // Seems like the first condition is to blame
    if (jsonAsMap.size >= in.count(_.codec.schema.isOptional) && jsonAsMap.size <= in.size) {
     // ....
    } else {
      val msg = "Too many inputs provided"
      DecodeResult.Error(msg, new RuntimeException(msg))
    }
  }
```
As far as I understand, when optional params are omitted, the first condition is always `false`. Maybe, we need just to check that actual ammount of params less or equal to number of inputs? 

**To Reproduce**
-  Describe a test endpoint, like this:
```
  val testEndpoint: JsonRpcEndpoint[Option[String], Unit, String] =
    jsonRpcEndpoint(m"echo")
      .in(param[Option[String]]("msg1").and(param[String]("msg2")))
      .out[String]("response")
```
- Provide some simple logic 
- Export (I use tapir endpoint and http4s interpreter)
- Send request without param, that is expected to be optional.
```
{
    "jsonrpc": "2.0",
    "id": "123",
    "method": "echo",
    "params": {
        "msg2": "Two Tiny Little Tigers"
    }
}
```

**Expected behavior**
Optional params are treated as `None`'s and cause no errors when decoded.

**Additional context**
Version: `0.1.0`

**Comment by amricko0b** [comment]
I did a one-line PR, that tries to fix it: https://github.com/input-output-hk/armadillo/pull/40

**Comment by ghostbuster91** [comment]
Hi, thank you for the nice words, and sorry for the delay. 

The bug is indeed there but I think that you have minimized your example a little bit too much, because for one optional parameter and one required the code actually works as expected because the faulty check:
`jsonAsMap.size >= in.count(_.codec.schema.isOptional)`
evaluates to:
`1 >= 1` 

We also have a test for that particular case: https://github.com/input-output-hk/armadillo/blob/main/server/test/src/io/iohk/armadillo/server/AbstractServerSuite.scala#L328

However it fails if you create an endpoint with two optional params and one required and omit the first two in the request.

**Comment by amricko0b** [comment]
Hi, @ghostbuster91 ! Thank you for feedback.

I provided new test cases on optional params and improved my little "patch" as you said. Sad, but I had to reopen my PR, because Github invalidated my fork repository and PR as well, for some reason (maybe it's my fault - I'm not a pro in contributing). 

Actual PR is now: https://github.com/input-output-hk/armadillo/pull/41
